[package]
name = "faultybot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.6"
openai = "1.0.0-alpha.6"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dependencies.tokio]
version = "1.26.0"
features = [ "macros", "signal", "rt-multi-thread" ]

[dependencies.serenity]
version = "0.11.5"
features = [ "cache", "framework", "standard_framework", "rustls_backend" ]
