[package]
name = "faultybot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = "1.0.4"
dotenvy = "0.15.6"
metrics = "0.20.1"
metrics-util = "0.14.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
lazy_static = "1.4.0"

[dependencies.metrics-exporter-prometheus]
version = "0.11.0"
default_features = false
features = [ "http-listener" ]

[dependencies.openai]
version = "1.0.0-alpha.8"
default_features = false
features = [ "rustls" ]

[dependencies.tokio]
version = "1.26.0"
features = [ "macros", "signal", "rt-multi-thread" ]

[dependencies.serenity]
version = "0.11.5"
features = [ "cache", "framework", "standard_framework", "rustls_backend" ]

[dependencies.reqwest]
version = "0.11.14"
default-features = false
features = [ "json", "rustls", "rustls-tls", "hyper-rustls", "tokio-rustls" ]