//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use super::sea_orm_active_enums::LlmModel;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "persona")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub guild_id: i64,
    pub prompt: String,
    pub model: LlmModel,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::active_persona::Entity")]
    ActivePersona,
}

impl Related<super::active_persona::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ActivePersona.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
