//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "effect")]
pub enum Effect {
    #[sea_orm(string_value = "Allow")]
    Allow,
    #[sea_orm(string_value = "Deny")]
    Deny,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "llm_model")]
pub enum LlmModel {
    #[sea_orm(string_value = "gpt-3.5-turbo")]
    Gpt35Turbo,
    #[sea_orm(string_value = "gpt-4")]
    Gpt4,
}
