use std::env;
use std::error::Error;
use std::net::SocketAddr;
use std::time::Duration;
use metrics::{describe_counter, describe_histogram};
use metrics_exporter_prometheus::PrometheusBuilder;
use metrics_exporter_statsd::StatsdBuilder;
use metrics_util::MetricKindMask;

pub(crate) fn init_metrics() {
    if install_prometheus_recorder().expect("Failed to install Prometheus recorder") {
        describe_metrics();
    } else if install_statsd_recorder().expect("Failed to install StatsD recorder") {
        // Nothing (yet?)
    }

}

/// We register these metrics, which gives us a chance to specify a description for them.  The
/// Prometheus exporter records this description and adds it as HELP text when the endpoint is
/// scraped.
///
/// Registering metrics ahead of using them is not required, but is the only way to specify the
/// description of a metric.
fn describe_metrics() {
    describe_counter!("faultybot_errors_total", "The total number of errors");
    describe_counter!("faultybot_gpt_requests_total", "The total number of response requests to FaultyGPT");
    describe_counter!("faultybot_gpt_responses_total", "The total number of responses provided by FaultyGPT");
    describe_histogram!(
        "faultybot_gpt_response_seconds",
        "The time take for a GPT a response to be generated by FaultyGPT"
    );
}

fn install_prometheus_recorder() -> Result<bool, Box<dyn Error>> {
    let address = match env::var("METRICS_LISTEN_ADDRESS") {
        Ok(addr) => addr.parse::<SocketAddr>()?,
        Err(_) => return Ok(false),
    };

    PrometheusBuilder::new()
        .idle_timeout(
            MetricKindMask::COUNTER | MetricKindMask::HISTOGRAM,
            Some(Duration::from_secs(10)),
        )
        .with_http_listener(address)
        .install()?;

    Ok(true)
}

fn install_statsd_recorder() -> Result<bool, Box<dyn Error>> {
    let host = match env::var("STATSD_HOST") {
        Ok(host) => host,
        Err(_) => return Ok(false),
    };
    let port = match env::var("STATSD_PORT") {
        Ok(port) => port.parse()?,
        Err(_) => return Ok(false),
    };

    let recorder = StatsdBuilder::from(host, port)
        .histogram_is_timer()
        .build(None)?;

    metrics::set_boxed_recorder(Box::new(recorder))?;

    Ok(true)
}
